baseURL: https://asankah.github.io/
languageCode: en-us
title: "Strong Opinions, Weakly Held"
copyright: "&copy; 2020 Asanka Herath"
theme: tale
ignoreFiles: [ "content/sources/*", "content/drafts/*" ]
googleAnalytics: UA-169355711-1
enableGitInfo: true
enableRobotsTXT: true
params:
        author: "Asanka Herath"
        rss:
                enable: true
                includeContent: true
        social:
                twitter: "@asankah"
                github: asankah
                email: "asanka@gmail.com"
                rss: "index.xml"
                linkedin: asankah
        mathjax: true
taxonomies:
        tag: "tags"

markup:
        defaultMarkdownHandler: "pandoc"

imaging:
        exif:
                excludeFields: ".*"
                disableDate: true
                disableLatLong: true


